### ISSUE TITLE
C atchops and Dart AtChops interoperability tests

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/at_mono#45]
Interoperability tests between the two crypto libraries is needed to ensure C is in-line with our canonical Dart cryptographic and hash operations library.

1. Generate test case table
2. Implement it maybe using named pipes between Dart and C programs?

**Comment by JeremyTubongbanua** [comment]
@XavierChanth I'd like to make interoperability tests between our crypto libraries a high priority because notifications cannot move further if the C atchops is not working correctly

**Comment by xavierchanth** [comment]
I'll start work on it today

**Comment by xavierchanth** [comment]
#46 prepares at_mono for these tests

**Comment by xavierchanth** [comment]
This can be a P2 or P3, #51 has covered the two most important cases: aesctr encrypt/decrypt between dart and c
